#!/usr/bin/env python3
"""Scrape real CoH1 stats from the coh-stats.com mirror into coh/data/tables/.

Run with `uv run python tools/scrape_coh_stats.py`. Fetched HTML is cached under
`tools/.cache/` (git-ignored); a second run is offline and byte-identical.

Inputs
    tools/roster.yaml       which pages are in scope, plus the handful of facts
                            the mirror does not state (weapon counts per squad,
                            building footprints, tech prerequisites)
    tools/patch_2602.yaml   forward-port of the official 2.602 release notes;
                            each entry's `old` is asserted against the scrape

Outputs (overwritten)
    coh/data/tables/weapons.yaml
    coh/data/tables/squads.yaml
    coh/data/tables/buildings.yaml
    coh/data/tables/upgrades.yaml

`economy.yaml` and `neutral.yaml` are hand-written (the mirror carries no
resource, territory or ambient-building data) and are not touched here.

Page anatomy, learned by inspection and relied on below:
  * Every unit/structure/upgrade page opens with one "stat block" table whose
    first row is a single <th> spanning the table; the rest is <th>label</th>
    <td>value</td> pairs, some with rowspan for the L/M/S range bands.
  * Costs are icon-separated: an <img src=".../Manpower.png"> precedes the
    manpower figure, etc. Never parse a cost from stripped text.
  * Weapon pages add a 12-row "Cover Table" and a 53-row "Target Table", both
    <table class="sortable">, identical in shape across all weapons.
  * Section bodies ("Constructs", "Upgrades", "Can Construct", ...) follow an
    <a name="..."></a><h2> anchor and link to the member pages.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

import requests
import yaml
from bs4 import BeautifulSoup, NavigableString, Tag

TOOLS_DIR = Path(__file__).resolve().parent
CACHE_DIR = TOOLS_DIR / ".cache"
TABLES_DIR = TOOLS_DIR.parent / "coh" / "data" / "tables"
ROSTER_PATH = TOOLS_DIR / "roster.yaml"
PATCH_PATH = TOOLS_DIR / "patch_2602.yaml"

OMG_ENTITIES_URL = "https://raw.githubusercontent.com/omgmod/omg_rails/master/lib/assets/stats/entities.json"
OMG_ENTITIES_CACHE = "omg_entities.json"
PATCH_NOTES_URL = "https://www.gamereplays.org/community/Official_CoH_2602_Release_Notes-t782742.html"

REQUEST_INTERVAL_S = 0.5
USER_AGENT = "coh-rl-env data scraper (one-off, cached)"

# Our range bands, shortest first; the pages label them S / M / L.
BAND_LETTERS = ("S", "M", "L")
BAND_NAMES = ("short", "medium", "long")

# Cover rows we model. The page also lists Default (always 1/1/1), Halftrack,
# Smoke, Trench, Water, Bunker, Emplacement and an "Open" row; see the module
# docstring of the report for why "Open" is not mapped onto our `open`.
COVER_ROWS = {"Light": "light", "Heavy": "heavy", "Negative": "negative", "Garrison": "garrison"}

RESOURCE_ICONS = {
    "Manpower.png": "manpower",
    "Munition.png": "munitions",
    "Fuel.png": "fuel",
    "Command.png": "command_points",
}

# Suppression thresholds for a unit the Info:Suppression page does not list.
STANDARD_INFANTRY_SUPPRESSION = {
    "suppress_at": 0.2,
    "suppress_recover": 0.15,
    "pin_at": 0.6,
    "pin_recover": 0.5,
    "recovery_per_s": 0.008,
}

SOURCE_LINE = (
    "coh-stats.com mirror https://www.hq-coh.com/stats/coh-stats.com/ "
    "(static Dec 2013 copy, data ~2.600/2.601), forward-ported with the official "
    f"2.602 release notes {PATCH_NOTES_URL}; infantry and team-weapon speed and "
    f"rotation from omgmod entities.json {OMG_ENTITIES_URL}. "
    "Generated by tools/scrape_coh_stats.py -- do not edit by hand."
)

FILE_BANNER = "# Generated by tools/scrape_coh_stats.py. Do not edit by hand.\n"


class ScrapeError(RuntimeError):
    """Raised when a page cannot be parsed or a patch precondition fails."""


# --- YAML output shaping ----------------------------------------------------------


class Flow(dict):
    """A mapping rendered on one line, for small records like `{manpower: 270}`."""


class FlowList(list):
    """A sequence rendered on one line, for tuples like `[8, 17, 35]`."""


yaml.SafeDumper.add_representer(
    Flow, lambda dumper, data: dumper.represent_mapping("tag:yaml.org,2002:map", data, flow_style=True)
)
yaml.SafeDumper.add_representer(
    FlowList, lambda dumper, data: dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)
)


def write_table(path: Path, source: str, estimated: dict[str, str], body: dict[str, Any]) -> None:
    doc: dict[str, Any] = {"source": source}
    if estimated:
        doc["estimated"] = estimated
    doc.update(body)
    text = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True)
    path.write_text(FILE_BANNER + text)


# --- fetching ---------------------------------------------------------------------


class Fetcher:
    """Fetches pages once, then serves them from `tools/.cache/`."""

    def __init__(self, base: str, *, offline: bool = False) -> None:
        self.base = base
        self.offline = offline
        self._last_request = 0.0
        CACHE_DIR.mkdir(parents=True, exist_ok=True)

    def _download(self, url: str, dest: Path) -> str:
        if self.offline:
            raise ScrapeError(f"{dest.name} not cached and --offline was given")
        wait = REQUEST_INTERVAL_S - (time.monotonic() - self._last_request)
        if wait > 0:
            time.sleep(wait)
        try:
            response = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=30)
            response.raise_for_status()
        except requests.RequestException as exc:  # pragma: no cover - network
            raise ScrapeError(f"could not fetch {url}: {exc}") from exc
        self._last_request = time.monotonic()
        dest.write_text(response.text, encoding="utf-8", errors="replace")
        return response.text

    def page(self, name: str) -> str:
        """Fetch a mirror page by its `Infantry_Riflemen` style name."""
        dest = CACHE_DIR / f"{name}.html"
        if dest.exists():
            return dest.read_text(encoding="utf-8", errors="replace")
        return self._download(f"{self.base}{name}.html", dest)

    def json_url(self, url: str, cache_name: str) -> Any:
        dest = CACHE_DIR / cache_name
        if not dest.exists():
            self._download(url, dest)
        return json.loads(dest.read_text(encoding="utf-8", errors="replace"))


# --- HTML helpers -----------------------------------------------------------------


def content_soup(html: str) -> BeautifulSoup:
    """Return the page body, stripped of the mirror's chrome and scripts."""
    start = html.find("<!-- start content -->")
    end = html.find("printfooter")
    if start < 0 or end < 0:
        raise ScrapeError("page has no recognisable content region")
    soup = BeautifulSoup(html[start:end], "html.parser")
    for script in soup.find_all("script"):
        script.decompose()
    return soup


Cell = tuple[Tag, bool, int]  # (cell, is_origin, rowspan)


def table_grid(table: Tag) -> dict[tuple[int, int], Cell]:
    """Expand a table into {(row, col): cell}, replicating row/colspan cells."""
    grid: dict[tuple[int, int], Cell] = {}
    rows = table.find_all("tr", recursive=False) or table.find_all("tr")
    for r, tr in enumerate(rows):
        c = 0
        for cell in tr.find_all(["td", "th"], recursive=False):
            while (r, c) in grid:
                c += 1
            rowspan = int(cell.get("rowspan", 1))
            colspan = int(cell.get("colspan", 1))
            for dr in range(rowspan):
                for dc in range(colspan):
                    grid[(r + dr, c + dc)] = (cell, dr == 0 and dc == 0, rowspan)
            c += colspan
    return grid


def cell_text(cell: Tag) -> str:
    return " ".join(cell.get_text(" ", strip=True).split())


class StatBlock:
    """The label/value table at the top of a unit, structure or upgrade page.

    Scalar labels resolve to the cell to their right. Labels with rowspan N (the
    L/M/S range bands) resolve to N (letter, value) pairs.
    """

    def __init__(self, table: Tag) -> None:
        self.table = table
        self.grid = table_grid(table)
        self.rows = max(r for r, _ in self.grid) + 1
        self.cols = max(c for _, c in self.grid) + 1
        self._labels: dict[str, tuple[int, int, int]] = {}
        for r in range(self.rows):
            for c in range(self.cols):
                entry = self.grid.get((r, c))
                if entry and entry[1] and entry[0].name == "th":
                    label = cell_text(entry[0])
                    if label and label not in self._labels:
                        self._labels[label] = (r, c, entry[2])

    def _locate(self, label: str) -> tuple[int, int, int] | None:
        if label in self._labels:
            return self._labels[label]
        for text, position in self._labels.items():
            if text.startswith(label + " "):  # e.g. "Range Max:35 Min:0"
                return position
        return None

    def label_text(self, label: str) -> str | None:
        position = self._locate(label)
        if position is None:
            return None
        row, col, _ = position
        return cell_text(self.grid[(row, col)][0])

    def cell(self, label: str) -> Tag | None:
        position = self._locate(label)
        if position is None:
            return None
        row, col, _ = position
        entry = self.grid.get((row, col + 1))
        return entry[0] if entry else None

    def text(self, label: str) -> str | None:
        cell = self.cell(label)
        return cell_text(cell) if cell is not None else None

    def bands(self, label: str) -> dict[str, str]:
        """Read an L/M/S band group into {letter: value}."""
        position = self._locate(label)
        if position is None:
            raise ScrapeError(f"missing band label {label!r}")
        row, col, rowspan = position
        out: dict[str, str] = {}
        for i in range(rowspan):
            letter = self.grid.get((row + i, col + 1))
            value = self.grid.get((row + i, col + 2))
            if letter is None or value is None:
                continue
            out[cell_text(letter[0])] = cell_text(value[0])
        missing = set(BAND_LETTERS) - set(out)
        if missing:
            raise ScrapeError(f"band label {label!r} is missing bands {sorted(missing)}")
        return out


def stat_block(soup: BeautifulSoup) -> StatBlock:
    """The first table whose header row is one <th> spanning the whole table."""
    for table in soup.find_all("table"):
        rows = table.find_all("tr", recursive=False)
        if not rows:
            continue
        cells = rows[0].find_all(["td", "th"], recursive=False)
        if len(cells) == 1 and cells[0].name == "th" and int(cells[0].get("colspan", 1)) >= 3:
            return StatBlock(table)
    raise ScrapeError("page has no stat block table")


def sections(soup: BeautifulSoup) -> dict[str, list[str]]:
    """{section anchor name: linked page names}, for the page's <h2> sections."""
    html = str(soup)
    anchors = [(m.start(), m.group(1)) for m in re.finditer(r'<a name="([^"]+)"></a><h2>', html)]
    out: dict[str, list[str]] = {}
    for index, (position, name) in enumerate(anchors):
        end = anchors[index + 1][0] if index + 1 < len(anchors) else len(html)
        pages: list[str] = []
        for href in re.findall(r'href="([^"]+\.html)"', html[position:end]):
            page = href[: -len(".html")]
            if page not in pages:
                pages.append(page)
        out[name] = pages
    return out


# --- value helpers ----------------------------------------------------------------

DASH = "—"  # coh-stats writes ranges as "min—max"


def numbers(text: str | None) -> list[float]:
    """The numbers in a cell like `3.5—2.5`, `-60—60` or `87.5`."""
    if text is None:
        raise ScrapeError("expected a numeric cell, found none")
    found = re.findall(r"-?\d+(?:\.\d+)?", text)
    if not found:
        raise ScrapeError(f"no number in {text!r}")
    return [float(x) for x in found]


INTEGER_SNAP_MIN = 5.0
INTEGER_SNAP_TOLERANCE = 0.05


def tidy(value: float) -> float | int:
    """Round away the mirror's float noise (260.01 -> 260, 39.99 -> 40).

    Snapping to an integer is only safe for the large quantities that carry the
    noise (costs, times, hit points); small multipliers such as the Engineers'
    0.02 suppression threshold must survive untouched.
    """
    if abs(value) >= INTEGER_SNAP_MIN and abs(value - round(value)) < INTEGER_SNAP_TOLERANCE:
        return int(round(value))
    rounded = round(value, 6)
    return int(rounded) if rounded == int(rounded) else rounded


def optional_number(block: StatBlock, label: str, default: float) -> float | int:
    text = block.text(label)
    if text is None or not text.strip():
        return tidy(default)
    return tidy(numbers(text)[0])


def band_tuple(block: StatBlock, label: str) -> FlowList:
    values = block.bands(label)
    return FlowList(tidy(numbers(values[letter])[0]) for letter in BAND_LETTERS)


def parse_cost(cell: Tag | None) -> Flow:
    """Costs are separated by resource icons, so read the icons, not the text.

    Infantry squad pages are the one exception: they print a bare manpower figure
    with no icon at all (`<th>Cost</th><td>260.01</td>`).
    """
    cost: dict[str, float] = {}
    if cell is None:
        return Flow()
    current: str | None = "manpower" if cell.find("img") is None else None
    for node in cell.descendants:
        if isinstance(node, Tag) and node.name == "img":
            current = RESOURCE_ICONS.get(node.get("src", "").rsplit("/", 1)[-1])
        elif isinstance(node, NavigableString):
            text = str(node).strip()
            if not text or current is None:
                continue
            for value in numbers(text):
                cost[current] = cost.get(current, 0.0) + value
    # Command points gate doctrinal unlocks only; nothing in the roster uses them.
    cost.pop("command_points", None)
    return Flow((key, tidy(value)) for key, value in cost.items() if value)


# --- weapons ----------------------------------------------------------------------


def sortable_tables(soup: BeautifulSoup) -> dict[str, list[list[str]]]:
    """The weapon page's Cover Table and Target Table, keyed by first header."""
    out: dict[str, list[list[str]]] = {}
    for table in soup.find_all("table"):
        classes = table.get("class") or []
        if "sortable" not in classes:
            continue
        rows = [[cell_text(c) for c in tr.find_all(["th", "td"])] for tr in table.find_all("tr")]
        if rows:
            out[rows[0][0]] = rows
    return out


def parse_weapon(soup: BeautifulSoup, spec: dict[str, Any], target_types: dict[str, str]) -> tuple[dict, float]:
    """Return (weapon record, horizontal traverse in degrees)."""
    block = stat_block(soup)

    damage_values = numbers(block.text("Damage"))
    burst_values = numbers(block.text("Burst Duration"))
    rof_values = numbers(block.text("Rate of Fire"))
    reload_frequency = max(numbers(block.text("Reload Frequency")))

    burst = None if max(burst_values) == 0 else FlowList(tidy(v) for v in sorted(burst_values))
    rate_of_fire = tidy(max(rof_values))
    if burst is None and rate_of_fire == 0:
        # Single-shot weapon: one bullet per firing cycle.
        rate_of_fire = 1

    range_label = block.label_text("Range") or ""
    min_range_match = re.search(r"Min:\s*(-?\d+(?:\.\d+)?)", range_label)
    if min_range_match is None:
        raise ScrapeError(f"no minimum range in {range_label!r}")

    record: dict[str, Any] = {
        "damage": tidy(sum(damage_values) / len(damage_values)),
        "ranges": band_tuple(block, "Range"),
        "min_range": tidy(float(min_range_match.group(1))),
        "accuracy": band_tuple(block, "Accuracy"),
        "penetration": band_tuple(block, "Penetration"),
        "suppression": band_tuple(block, "Suppression"),
        "cooldown": FlowList(tidy(v) for v in sorted(numbers(block.text("Cooldown")))),
        "cooldown_range_mult": band_tuple(block, "Cooldown Multiplier"),
        "burst": burst,
        "rate_of_fire": rate_of_fire,
        "reload": FlowList(tidy(v) for v in sorted(numbers(block.text("Reload")))),
        # "The actual clip size is Reload Frequency + 1"; 0 means "reload every shot".
        "reload_every": max(1, int(reload_frequency)),
        "setup_time": tidy(numbers(block.text("Setup Time"))[0]),
        "moving_accuracy": tidy(numbers(block.text("Moving Accuracy"))[0]),
        "nearby_suppression_mult": tidy(numbers(block.text("Nearby Supp. Multiplier"))[0]),
        "nearby_suppression_radius": tidy(numbers(block.text("Nearby Supp. Radius"))[0]),
        "aoe_radius": tidy(numbers(block.bands("AOE Distance")["L"])[0]),
        "deflection_damage_mult": tidy(numbers(block.text("Deflection Multiplier"))[0]),
    }

    if spec.get("indirect"):
        scatter_max = numbers(block.text("Scatter Max"))[0]
        scatter_ratio = numbers(block.text("Scatter Ratio"))[0]
        record["indirect"] = True
        record["scatter_m"] = tidy(scatter_max * scatter_ratio)

    tables = sortable_tables(soup)
    cover_rows = tables.get("Cover Type")
    target_rows = tables.get("Target Name")
    if cover_rows is None or target_rows is None:
        raise ScrapeError("weapon page is missing its cover or target table")

    cover_table: dict[str, Flow] = {}
    for row in cover_rows[1:]:
        key = COVER_ROWS.get(row[0])
        if key is None:
            continue
        accuracy, damage, suppression = (float(row[1]), float(row[2]), float(row[3]))
        cover_table[key] = Flow(
            accuracy=tidy(accuracy), damage=tidy(damage), suppression=tidy(suppression)
        )
    if set(cover_table) != set(COVER_ROWS.values()):
        raise ScrapeError(f"cover table is missing rows: {sorted(set(COVER_ROWS.values()) - set(cover_table))}")

    target_table: dict[str, Flow] = {}
    for row in target_rows[1:]:
        key = target_types.get(row[0])
        if key is None:
            continue
        target_table[key] = Flow(
            accuracy=tidy(float(row[1])),
            moving=tidy(float(row[2])),
            damage=tidy(float(row[3])),
            penetration=tidy(float(row[4])),
            rear_penetration=tidy(float(row[5])),
            suppression=tidy(float(row[6])),
            priority=tidy(float(row[7])),
        )
    missing_targets = set(target_types.values()) - set(target_table)
    if missing_targets:
        raise ScrapeError(f"target table is missing rows: {sorted(missing_targets)}")

    record["cover_table"] = cover_table
    record["target_table"] = target_table

    traverse = numbers(block.text("Tracking Horizontal"))
    return record, max(traverse) - min(traverse)


# --- suppression ------------------------------------------------------------------

SUPPRESSION_HEADER = ["Units", "SAT", "SRT", "PAT", "PRT", "Rec Rate"]
SUPPRESSION_FACTIONS = ("us", "wehr")  # page order: American, Wehrmacht, CW, PE


def parse_suppression(soup: BeautifulSoup) -> dict[tuple[str, str], Flow]:
    """{(faction, unit name): suppression record} from Info:Suppression."""
    out: dict[tuple[str, str], Flow] = {}
    index = 0
    for table in soup.find_all("table"):
        rows = [[cell_text(c) for c in tr.find_all(["th", "td"])] for tr in table.find_all("tr")]
        if not rows or rows[0] != SUPPRESSION_HEADER:
            continue
        if index >= len(SUPPRESSION_FACTIONS):
            break
        faction = SUPPRESSION_FACTIONS[index]
        index += 1
        for row in rows[1:]:
            if len(row) != 6:
                continue
            out[(faction, row[0])] = Flow(
                suppress_at=tidy(float(row[1])),
                suppress_recover=tidy(float(row[2])),
                pin_at=tidy(float(row[3])),
                pin_recover=tidy(float(row[4])),
                recovery_per_s=float(row[5]),
            )
    if index < len(SUPPRESSION_FACTIONS):
        raise ScrapeError("Info:Suppression is missing the American or Wehrmacht threshold table")
    return out


# --- omgmod entities --------------------------------------------------------------


def parse_entities(payload: Any) -> dict[str, dict[str, str]]:
    return {entry["reference"]: (entry.get("moving") or {}) for entry in payload}


# --- squads -----------------------------------------------------------------------


def parse_squad(
    soup: BeautifulSoup,
    squad_id: str,
    spec: dict[str, Any],
    suppression: dict[tuple[str, str], Flow],
    entities: dict[str, dict[str, str]],
    estimated: dict[str, str],
) -> dict[str, Any]:
    block = stat_block(soup)
    kind = spec["kind"]
    faction = spec["faction"]
    entity_ref = spec.get("entity")
    entity = entities.get(entity_ref, {}) if entity_ref else {}

    loadout = FlowList()
    for weapon_id, count in spec["loadout"]:
        loadout.extend([weapon_id] * int(count))

    if kind == "vehicle":
        members = 1
        member_hp = tidy(numbers(block.text("Health"))[0])
        speed = tidy(numbers(block.text("Max Speed"))[0])
        rotation = tidy(numbers(block.text("Rotation"))[0])
        crushes = bool(entity.get("pass_type"))
        record_suppression = None
        capture_rate: float | int = 0
        reinforce_cost_mult: float | int = 0
        reinforce_time_mult: float | int = 0
        retreat_accuracy: float | int = 1
        upgrade_slots = 0
    else:
        # Towed guns live in the Vehicle: namespace and describe their crew
        # separately from the gun; infantry pages describe the squad directly.
        if block.text("Squad Size") is not None:
            # Infantry pages: "Health" is the whole squad's pool.
            members = int(numbers(block.text("Squad Size"))[0])
            member_hp = tidy(numbers(block.text("Health"))[0] / members)
        elif block.text("Crew Size") is not None:
            # Towed-gun pages: "Crew Health" is already per crew model, and
            # "Health" belongs to the gun itself (not modelled).
            members = int(numbers(block.text("Crew Size"))[0])
            member_hp = tidy(numbers(block.text("Crew Health"))[0])
            estimated[f"{squad_id}.member_hp"] = (
                "Crew health per model, taken as-is. The gun platform's own "
                f"{tidy(numbers(block.text('Health'))[0])} hit points are dropped: SquadDef has "
                "no separate weapon-platform pool, so killing the crew kills the gun."
            )
        else:
            raise ScrapeError(f"{squad_id}: no squad size / crew size on the page")
        speed = tidy(float(entity.get("speed_max", 3.0)))
        rotation = tidy(float(entity.get("rotation_rate", 150.0)))
        crushes = False
        upgrade_slots = int(optional_number(block, "Squad Slots", 0))

        suppression_key = spec.get("suppression_key")
        if suppression_key:
            record_suppression = suppression.get((faction, suppression_key))
            if record_suppression is None:
                raise ScrapeError(f"{squad_id}: no Info:Suppression row for {suppression_key!r}")
        else:
            record_suppression = Flow(STANDARD_INFANTRY_SUPPRESSION)
            estimated[f"{squad_id}.suppression"] = (
                "Info:Suppression has no row for towed guns; standard infantry thresholds assumed."
            )

        if block.text("Capture Rate") is None:
            capture_rate = 0
            estimated[f"{squad_id}.capture_rate"] = (
                "Towed-gun pages carry no capture rate; towed guns cannot capture in CoH1."
            )
        else:
            capture_rate = tidy(numbers(block.text("Capture Rate"))[0])

        if block.text("Reinforce Cost") is None:
            reinforce_cost_mult, reinforce_time_mult, retreat_accuracy = 0.5, 1, 0.5
            estimated[f"{squad_id}.reinforce_cost_mult"] = (
                "Towed-gun pages carry no reinforce/retreat modifiers; the other team "
                "weapons' values (0.5 cost, 1.0 time, 0.5 received accuracy) assumed."
            )
        else:
            reinforce_cost_mult = tidy(numbers(block.text("Reinforce Cost"))[0])
            reinforce_time_mult = tidy(numbers(block.text("Reinforce Time"))[0])
            retreat_accuracy = tidy(numbers(block.text("Retreat Modifier"))[0])

    if kind != "vehicle" and "speed_max" not in entity:
        estimated[f"{squad_id}.speed"] = (
            f"omgmod entities.json has no speed for {entity_ref!r}; 3.0 m/s "
            "(standard infantry) and 150 deg/s assumed."
        )

    return {
        "faction": faction,
        "kind": kind,
        "members": members,
        "member_hp": member_hp,
        "loadout": loadout,
        "target_type": block.text("Target Type"),
        "cost": parse_cost(block.cell("Cost")),
        "population": int(numbers(block.text("Population"))[0]),
        "build_time": tidy(numbers(block.text("Time"))[0]),
        "upkeep_per_min": tidy(numbers(block.text("Upkeep"))[0]),
        "speed": speed,
        "rotation_deg_s": rotation,
        "sight": tidy(numbers(block.text("Sight"))[0]),
        "capture_rate": capture_rate,
        "builds": FlowList(spec.get("builds", [])),
        "suppression": record_suppression,
        "reinforce_cost_mult": reinforce_cost_mult,
        "reinforce_time_mult": reinforce_time_mult,
        "retreat_received_accuracy": retreat_accuracy,
        "upgrade_slots": upgrade_slots,
        "crushes_light_cover": crushes,
        "can_garrison": bool(spec.get("can_garrison", False)),
    }


# --- buildings / upgrades ---------------------------------------------------------


def parse_building(
    soup: BeautifulSoup,
    spec: dict[str, Any],
    squad_by_page: dict[str, str],
    upgrade_by_page: dict[str, str],
) -> dict[str, Any]:
    block = stat_block(soup)
    page_sections = sections(soup)
    produces = [squad_by_page[p] for p in page_sections.get("Constructs", []) if p in squad_by_page]
    researches = [upgrade_by_page[p] for p in page_sections.get("Upgrades", []) if p in upgrade_by_page]
    return {
        "faction": spec["faction"],
        "cost": parse_cost(block.cell("Cost")),
        "build_time": tidy(numbers(block.text("Time"))[0]),
        "hp": tidy(numbers(block.text("Health"))[0]),
        "target_type": block.text("Target Type"),
        "footprint": FlowList(int(x) for x in spec["footprint"]),
        "produces": FlowList(produces),
        "researches": FlowList(researches),
        "requires": FlowList(spec["requires"]),
        "is_hq": bool(spec["is_hq"]),
        "reinforce_radius": optional_number(block, "Reinforce Radius", 0),
        "sight": tidy(numbers(block.text("Sight"))[0]),
    }


def parse_upgrade(soup: BeautifulSoup, spec: dict[str, Any]) -> dict[str, Any]:
    block = stat_block(soup)
    record = {
        "faction": spec["faction"],
        "cost": parse_cost(block.cell("Cost")),
        "time": tidy(numbers(block.text("Time"))[0]),
        "requires": FlowList(spec["requires"]),
    }
    if "upkeep_mult" in spec:
        record["upkeep_mult"] = spec["upkeep_mult"]
    return record


def parse_squad_upgrade(soup: BeautifulSoup, spec: dict[str, Any]) -> dict[str, Any]:
    block = stat_block(soup)
    return {
        "applies_to": FlowList(spec["applies_to"]),
        "cost": parse_cost(block.cell("Cost")),
        "time": tidy(numbers(block.text("Time"))[0]),
        "requires": FlowList(spec["requires"]),
        "weapon": spec["weapon"],
        "count": int(spec["count"]),
    }


# --- 2.602 patching ---------------------------------------------------------------


def apply_patch(tables: dict[str, dict[str, Any]], patches: list[dict[str, Any]]) -> None:
    """Apply each `{table, id, field, old, new}`, asserting `old` first."""
    for patch in patches:
        table_name, entry_id, field = patch["table"], patch["id"], patch["field"]
        table = tables.get(table_name)
        if table is None or entry_id not in table:
            raise ScrapeError(f"patch target {table_name}:{entry_id} was not scraped")
        container: Any = table[entry_id]
        keys = field.split(".")
        for key in keys[:-1]:
            container = _descend(container, key, f"{table_name}:{entry_id}:{field}")
        leaf = keys[-1]
        index = _key_or_index(container, leaf, f"{table_name}:{entry_id}:{field}")
        actual = container[index]
        if abs(float(actual) - float(patch["old"])) > 1e-9:
            raise ScrapeError(
                f"patch {table_name}:{entry_id}:{field} expected old value {patch['old']}, "
                f"scraped {actual}"
            )
        container[index] = tidy(float(patch["new"]))


def _descend(container: Any, key: str, where: str) -> Any:
    return container[_key_or_index(container, key, where)]


def _key_or_index(container: Any, key: str, where: str) -> Any:
    if isinstance(container, list):
        if key not in BAND_NAMES:
            raise ScrapeError(f"patch {where}: {key!r} is not a range band")
        return BAND_NAMES.index(key)
    if key not in container:
        raise ScrapeError(f"patch {where}: no field {key!r}")
    return key


# --- main -------------------------------------------------------------------------


def build_tables(fetcher: Fetcher, roster: dict[str, Any]) -> dict[str, tuple[dict, dict]]:
    """Scrape everything. Returns {table name: (body, estimated notes)}."""
    target_types = roster["target_types"]
    squad_specs = roster["squads"]
    squad_by_page = {spec["page"]: sid for sid, spec in squad_specs.items()}
    upgrade_by_page = {spec["page"]: uid for uid, spec in roster["upgrades"].items()}

    entities = parse_entities(fetcher.json_url(OMG_ENTITIES_URL, OMG_ENTITIES_CACHE))
    suppression = parse_suppression(content_soup(fetcher.page("Info_Suppression")))

    # Weapons carried by foot infantry rotate freely, so their traverse is not a
    # firing arc; team weapons and vehicle mounts keep the page's traverse.
    free_aiming: set[str] = set()
    for spec in squad_specs.values():
        if spec["kind"] == "infantry":
            free_aiming.update(weapon for weapon, _ in spec["loadout"] if weapon)
    for spec in roster["squad_upgrades"].values():
        if all(squad_specs[s]["kind"] == "infantry" for s in spec["applies_to"]):
            free_aiming.add(spec["weapon"])

    weapons: dict[str, Any] = {}
    weapons_estimated: dict[str, str] = {
        "*.cover_table": (
            "The page's 'Open' cover row (accuracy 1.25) is a distinct cover type that "
            "coh-stats' own Info:Weapon Statistics records as unused in game, so it is "
            "not emitted; our `open` (= no cover) falls back to the identity mods, which "
            "equal the page's 'Default' row (1/1/1) for every weapon scraped."
        ),
        "*.cover_table.penetration": (
            "The page's cover table has a penetration column (e.g. 37 mm Greyhound vs "
            "heavy cover 0.5); CoverMods has no penetration field, so it is dropped."
        ),
        "*.damage": "Pages give a min-max damage pair; the mean is used (equal for all but flame weapons).",
        "*.rate_of_fire": "Single-shot weapons list 0 bullets/s; 1 bullet per firing cycle is used instead.",
    }
    traverses: dict[str, float] = {}
    for weapon_id, spec in roster["weapons"].items():
        soup = content_soup(fetcher.page(spec["page"]))
        record, traverse = parse_weapon(soup, spec, target_types)
        traverses[weapon_id] = traverse
        weapons[weapon_id] = record
        if spec.get("indirect"):
            weapons_estimated[f"{weapon_id}.scatter_m"] = (
                "Derived as the page's Scatter Max x Scatter Ratio; the source models "
                "scatter as an angle plus distance ratio, not a metre standard deviation."
            )

    for weapon_id, record in weapons.items():
        if weapon_id in free_aiming:
            record["arc_deg"] = 360
        else:
            record["arc_deg"] = tidy(traverses[weapon_id])

    squads: dict[str, Any] = {}
    squads_estimated: dict[str, str] = {
        "*.loadout": (
            "Squad pages list which weapons a squad carries but not how many of each; "
            "the per-weapon counts come from tools/roster.yaml."
        ),
    }
    for squad_id, spec in squad_specs.items():
        soup = content_soup(fetcher.page(spec["page"]))
        squads[squad_id] = parse_squad(soup, squad_id, spec, suppression, entities, squads_estimated)
        if spec["kind"] == "vehicle":
            squads_estimated.setdefault(
                "*.retreat_received_accuracy (vehicles)",
                "Vehicle pages carry no retreat modifier; vehicles do not retreat, so 1.0 is used.",
            )

    buildings: dict[str, Any] = {}
    buildings_estimated = {
        "*.footprint": "The mirror carries no building dimensions; footprints are authored in tools/roster.yaml.",
        "*.requires": (
            "Prerequisites are not on the structure pages except Supply Yard's "
            "'Barracks OR Weapons Support Center'. `requires` is all-of, so that OR is "
            "approximated by Barracks. Motor Pool and Tank Depot requiring the Supply "
            "Yard is from the Supply Yard page's Unlocks section, cross-checked on the "
            "fandom wiki. Wehrmacht gating is the Reich HQ phase chain."
        ),
    }
    for building_id, spec in roster["buildings"].items():
        soup = content_soup(fetcher.page(spec["page"]))
        buildings[building_id] = parse_building(soup, spec, squad_by_page, upgrade_by_page)

    upgrades: dict[str, Any] = {}
    for upgrade_id, spec in roster["upgrades"].items():
        soup = content_soup(fetcher.page(spec["page"]))
        upgrades[upgrade_id] = parse_upgrade(soup, spec)

    squad_upgrades: dict[str, Any] = {}
    for upgrade_id, spec in roster["squad_upgrades"].items():
        soup = content_soup(fetcher.page(spec["page"]))
        squad_upgrades[upgrade_id] = parse_squad_upgrade(soup, spec)

    upgrades_estimated = {
        "supply_yard_l1.upkeep_mult": (
            "From the Supply Yard page's effect text ('Decrease the Upkeep cost of your "
            "Troops by 25%'); the mirror has no numeric upkeep field for upgrades."
        ),
        "supply_yard_l2.upkeep_mult": (
            "From 'Decrease the Upkeep cost of your Troops by an additional 25%', applied "
            "multiplicatively on top of level 1."
        ),
        "*.count": (
            "Squad-upgrade pages give cost, time, weapon and eligible squads but not how "
            "many models receive the weapon; counts are authored in tools/roster.yaml."
        ),
    }

    patches = yaml.safe_load(PATCH_PATH.read_text())["patches"]
    apply_patch({"weapons": weapons, "squads": squads}, patches)

    return {
        "weapons": ({"weapons": weapons}, weapons_estimated),
        "squads": ({"squads": squads}, squads_estimated),
        "buildings": ({"buildings": buildings}, buildings_estimated),
        "upgrades": ({"upgrades": upgrades, "squad_upgrades": squad_upgrades}, upgrades_estimated),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true", help="fail instead of fetching uncached pages")
    args = parser.parse_args(argv)

    roster = yaml.safe_load(ROSTER_PATH.read_text())
    fetcher = Fetcher(roster["source_base"], offline=args.offline)
    try:
        tables = build_tables(fetcher, roster)
    except ScrapeError as exc:
        print(f"scrape failed: {exc}", file=sys.stderr)
        return 1

    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    for name, (body, estimated) in tables.items():
        path = TABLES_DIR / f"{name}.yaml"
        write_table(path, SOURCE_LINE, estimated, body)
        count = sum(len(v) for v in body.values())
        print(f"wrote {path.relative_to(TABLES_DIR.parents[2])} ({count} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
